//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoicingImport.Data {
    using System.Collections.Generic;

    public partial class Address
    {
        public Address()
        {
            this.Contacts = new HashSet<Contact>();
            this.Contacts1 = new HashSet<Contact>();
        }
    
        public int AddressId { get; set; }
        public int ContactId { get; set; }
        public string Name { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public string ZIP { get; set; }
        public string Country { get; set; }
    
        public virtual Contact Contact { get; set; }
        public virtual ICollection<Contact> Contacts { get; set; }
        public virtual ICollection<Contact> Contacts1 { get; set; }
    }
}
