//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoicingImport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public Contact()
        {
            this.Addresses = new HashSet<Address>();
            this.Invoices = new HashSet<Invoice>();
        }
    
        public int ContactId { get; set; }
        public string CompanyName { get; set; }
        public string ICO { get; set; }
        public string DIC { get; set; }
        public string ContactName { get; set; }
        public string ContactEmail { get; set; }
        public string ContactPhone { get; set; }
        public string ContactFax { get; set; }
        public string ContactMobile { get; set; }
        public Nullable<int> DefaultBillAddressId { get; set; }
        public Nullable<int> DefaultPostalAddressId { get; set; }
        public string BankAccountNumber { get; set; }
        public System.Guid AccessCode { get; set; }
    
        public virtual ICollection<Address> Addresses { get; set; }
        public virtual Address DefaultBillAddress { get; set; }
        public virtual Address DefaultPostalAddress { get; set; }
        public virtual ICollection<Invoice> Invoices { get; set; }
    }
}
