//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoicingImport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int PaymentId { get; set; }
        public int InvoiceId { get; set; }
        public int PaymentMethod { get; set; }
        public System.DateTime DateReceived { get; set; }
        public decimal Amount { get; set; }
        public string Notes { get; set; }
    
        public virtual Invoice Invoice { get; set; }
        public virtual PaymentMethod PaymentMethod1 { get; set; }
    }
}
